// temp methods for trying out designs and data form

import axios from 'axios';
import {Item} from './classes/ItemModels'


export function getItems(): Item[]{
    
    axios.get('https://cat-fact.herokuapp.com/facts/random?animal_type=cat&amount=5')
        .then(response => console.log(response));
    console.log('double check');
    return mockItemList;
}

export function writeItems(items: Item[]): boolean{
    let success = false;
    
    return success;
}




const mockItemList: Array<Item> =
[
    {
      "Type": "Weapon",
      "Name": "Battle Axe",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": false,
      "IsEquippable": true,
      "AmmunitionType": "",
      "Damage": "1d8",
      "DamageLarge": "*",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 7,
      "Size": "Medium",
      "WeaponType": "S",
      "SpeedFactor": 7,
      "Cost": '5',
      "Special": ""
    },
    {
      "Type": "Weapon",
      "Name": "Morning Star",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": false,
      "IsEquippable": true,
      "AmmunitionType": "",
      "Damage": "2d4",
      "DamageLarge": "1d6 + 1",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 12,
      "Size": "Medium",
      "WeaponType": "P/B",
      "SpeedFactor": 7,
      "Cost": '10',
      "Special": ""
    },
    {
      "Type": "Armor",
      "Name": "Chain Mail",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": false,
      "IsEquippable": true,
      "AmmunitionType": "",
      "Damage": "",
      "DamageLarge": "",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 0,
      "Size": "",
      "WeaponType": "",
      "SpeedFactor": 0,
      "Cost": "",
      "Special": ""
    },
    {
      "Type": "Armor",
      "Name": "Leather",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": false,
      "IsEquippable": true,
      "AmmunitionType": "",
      "Damage": "",
      "DamageLarge": "",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 0,
      "Size": "",
      "WeaponType": "",
      "SpeedFactor": 0,
      "Cost": "",
      "Special": ""
    },
    {
      "Type": "Potion",
      "Name": "Potion of Healing",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": true,
      "IsEquippable": false,
      "AmmunitionType": "",
      "Damage": "",
      "DamageLarge": "",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 0,
      "Size": "",
      "WeaponType": "",
      "SpeedFactor": 0,
      "Cost": "",
      "Special": ""
    },
    {
      "Type": "Potion",
      "Name": "Potion of Giant Strength",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": true,
      "IsEquippable": false,
      "AmmunitionType": "",
      "Damage": "",
      "DamageLarge": "",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 0,
      "Size": "",
      "WeaponType": "",
      "SpeedFactor": 0,
      "Cost": "",
      "Special": ""
    },
    {
      "Type": "Scroll",
      "Name": "",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": true,
      "IsEquippable": false,
      "AmmunitionType": "",
      "Damage": "",
      "DamageLarge": "",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 0,
      "Size": "",
      "WeaponType": "",
      "SpeedFactor": 0,
      "Cost": "",
      "Special": ""
    },
    {
      "Type": "Scroll",
      "Name": "",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": true,
      "IsEquippable": false,
      "AmmunitionType": "",
      "Damage": "",
      "DamageLarge": "",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 0,
      "Size": "",
      "WeaponType": "",
      "SpeedFactor": 0,
      "Cost": "",
      "Special": ""
    },
    {
      "Type": "Weapon",
      "Name": "Blowgun",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": false,
      "IsEquippable": true,
      "AmmunitionType": "Dart",
      "Damage": "*",
      "DamageLarge": "",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 2,
      "Size": "",
      "WeaponType": "*",
      "SpeedFactor": 5,
      "Cost": '5',
      "Special": ""
    },
    {
      "Type": "Weapon",
      "Name": "Long Bow",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": false,
      "IsEquippable": true,
      "AmmunitionType": "Arrow",
      "Damage": "*",
      "DamageLarge": "",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 3,
      "Size": "",
      "WeaponType": "*",
      "SpeedFactor": 8,
      "Cost": '75',
      "Special": ""
    },
    {
      "Type": "Ammunition",
      "Name": "Needle",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": true,
      "IsEquippable": false,
      "AmmunitionType": "",
      "Damage": '1',
      "DamageLarge": "*",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 0.1,
      "Size": "",
      "WeaponType": "P",
      "SpeedFactor": 0,
      "Cost": "2cp",
      "Special": ""
    },
    {
      "Type": "Ammunition",
      "Name": "Sheaf Arrow",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": true,
      "IsEquippable": false,
      "AmmunitionType": "",
      "Damage": "1d8",
      "DamageLarge": "*",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 0.1,
      "Size": "",
      "WeaponType": "P",
      "SpeedFactor": 0,
      "Cost": "3 sp/6",
      "Special": ""
    },
    {
      "Type": "Wand/Staff/Rod",
      "Name": "",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": false,
      "IsEquippable": true,
      "AmmunitionType": "",
      "Damage": "",
      "DamageLarge": "",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 7,
      "Size": "",
      "WeaponType": "",
      "SpeedFactor": 0,
      "Cost": "",
      "Special": ""
    },
    {
      "Type": "Armor",
      "Name": "Buckler",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": false,
      "IsEquippable": true,
      "AmmunitionType": "",
      "Damage": "",
      "DamageLarge": "",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 4,
      "Size": "",
      "WeaponType": "",
      "SpeedFactor": 0,
      "Cost": "",
      "Special": ""
    },
    {
      "Type": "Armor",
      "Name": "Studded Leather",
      "ImagePath": "",
      "Description": "",
      "Charges": 0,
      "Buff": [],
      "IsSingleUse": false,
      "IsEquippable": true,
      "AmmunitionType": "",
      "Damage": "",
      "DamageLarge": "",
      "DamageTwoHand": "",
      "DamageTwoHandLarge": "",
      "Weight": 12,
      "Size": "",
      "WeaponType": "",
      "SpeedFactor": 0,
      "Cost": "",
      "Special": ""
    }
  ]